id: jenkins-panel

info:
  name: Jenkins Panel Detection
  author: moon-gazing-tower
  severity: info
  description: Detects Jenkins CI/CD panel.
  tags: panel,jenkins,cicd
  reference:
    - https://www.jenkins.io/

http:
  - method: GET
    path:
      - "{{BaseURL}}/login"
      - "{{BaseURL}}/jenkins/login"

    matchers-condition: and
    matchers:
      - type: word
        words:
          - "Jenkins"
          - "hudson"
        condition: or

      - type: status
        status:
          - 200
          - 403

    extractors:
      - type: regex
        name: version
        regex:
          - 'Jenkins ver\. ([\d.]+)'
        group: 1
