id: phpmyadmin-panel

info:
  name: phpMyAdmin Panel Detection
  author: moon-gazing-tower
  severity: info
  description: Detects phpMyAdmin panel.
  tags: panel,phpmyadmin,database
  reference:
    - https://www.phpmyadmin.net/

http:
  - method: GET
    path:
      - "{{BaseURL}}/phpmyadmin/"
      - "{{BaseURL}}/phpMyAdmin/"
      - "{{BaseURL}}/pma/"
      - "{{BaseURL}}/mysql/"
      - "{{BaseURL}}/myadmin/"
      - "{{BaseURL}}/admin/phpmyadmin/"

    stop-at-first-match: true

    matchers-condition: and
    matchers:
      - type: word
        words:
          - "phpMyAdmin"
          - "pma_password"
          - "pmahomme"
        condition: or

      - type: status
        status:
          - 200
          - 401

    extractors:
      - type: regex
        name: version
        regex:
          - 'phpMyAdmin\s*([\d.]+)'
        group: 1
