version: 0.7
user_agent: ""			# 自定义 User-Agent（可设置为获取Cookie的浏览器）
app:
  miit_api: ''          # HG-ha的ICP_Query (非狼组维护 https://github.com/HG-ha/ICP_Query) 
api:
  api: ':31000'    # API监听地址
  mcp: 'http://localhost:8080'    # MCP SSE监听地址
cookies:
  aiqicha: ''           # 爱企查   Cookie
  tianyancha: ''        # 天眼查   Cookie
  tycid: ''        		# 天眼查   CApi ID(capi.tianyancha.com)
  auth_token: ''        # 天眼查   Token (capi.tianyancha.com)
  tyc_api_token: ''     # 天眼查   官方API Key(https://open.tianyancha.com)
  risk_bird: '' 		# 风鸟     Cookie
  qimai: ''             # 七麦数据 Cookie
