id: xss-reflected

info:
  name: Reflected XSS Detection
  author: moon-gazing-tower
  severity: medium
  description: Detects potential reflected XSS vulnerabilities.
  tags: xss,injection
  classification:
    cwe-id: CWE-79

http:
  - method: GET
    path:
      - "{{BaseURL}}/?q=<script>alert(1)</script>"
      - "{{BaseURL}}/?search=<img%20src=x%20onerror=alert(1)>"
      - "{{BaseURL}}/?name=<svg%20onload=alert(1)>"

    stop-at-first-match: true

    matchers-condition: and
    matchers:
      - type: word
        part: body
        words:
          - "<script>alert(1)</script>"
          - "<img src=x onerror=alert(1)>"
          - "<svg onload=alert(1)>"
        condition: or

      - type: word
        part: header
        words:
          - "text/html"
        condition: and

      - type: status
        status:
          - 200
