# CDN检测配置
# CDN Detection Configuration

# CNAME Patterns - CNAME特征映射
cname_patterns:
  # 国内CDN
  cdn.dnsv1.com: "腾讯云CDN"
  tdnsv: "腾讯云CDN"
  tcdn: "腾讯云CDN"
  kunlun: "阿里云CDN"
  alikunlun: "阿里云CDN"
  alicdn: "阿里云CDN"
  aliyuncs: "阿里云CDN"
  tbcache: "淘宝CDN"
  cdngslb: "阿里云CDN"
  kunlunar: "阿里云CDN"
  wscdns: "网宿CDN"
  wscloudcdn: "网宿CDN"
  chinanetcenter: "网宿CDN"
  ccgslb: "网宿CDN"
  lxdns: "网宿CDN"
  cdn20: "网宿CDN"
  ourwebcdn: "网宿CDN"
  wswebpic: "网宿CDN"
  bsclink: "网宿CDN"
  speedcdns: "网宿CDN"
  bdydns: "百度云CDN"
  bdimg: "百度CDN"
  baiduyun: "百度云CDN"
  bcebos: "百度云CDN"
  hwcdn: "华为云CDN"
  hwclouds-cdn: "华为云CDN"
  cdnhwc: "华为云CDN"
  myhuaweicloud: "华为云CDN"
  jdcdn: "京东云CDN"
  jcloudlb: "京东云CDN"
  jcloud-cdn: "京东云CDN"
  ucloud: "UCloud CDN"
  ucloudgda: "UCloud CDN"
  aicdn: "又拍云CDN"
  upyun: "又拍云CDN"
  cdn.upyun: "又拍云CDN"
  qiniu: "七牛云CDN"
  qiniudns: "七牛云CDN"
  qbox: "七牛云CDN"
  clouddn: "七牛云CDN"
  ksyun: "金山云CDN"
  ks-cdn: "金山云CDN"
  speedycloud: "迅达云CDN"
  jiashule: "加速乐CDN"
  yunjiasu: "百度云加速"
  cdnzz: "CDNZZ"
  verygslb: "蓝汛CDN"
  chinacache: "蓝汛CDN"
  lxcdn: "蓝汛CDN"
  dnion: "帝联CDN"
  ewcache: "帝联CDN"
  globalcdn: "帝联CDN"
  fastweb: "快网CDN"
  fastcdn: "快网CDN"
  mschcdn: "中国移动CDN"
  ctcdn: "中国电信CDN"
  cncssr: "中国联通CDN"

  # 国际CDN
  cloudflare: "Cloudflare"
  fastly: "Fastly"
  fastlylb: "Fastly"
  akamai: "Akamai"
  akamaitech: "Akamai"
  akamaiedge: "Akamai"
  akadns: "Akamai"
  edgekey: "Akamai"
  edgesuite: "Akamai"
  cloudfront: "AWS CloudFront"
  amazonaws: "AWS CloudFront"
  azureedge: "Azure CDN"
  msecnd: "Azure CDN"
  vo.msecnd: "Azure CDN"
  azurefd: "Azure Front Door"
  googleusercontent: "Google Cloud CDN"
  googlesyndication: "Google CDN"
  gstatic: "Google CDN"
  incapdns: "Imperva"
  impervadns: "Imperva"
  sucuri: "Sucuri"
  stackpathdns: "StackPath"
  stackpath: "StackPath"
  netlify: "Netlify"
  vercel-dns: "Vercel"
  now.sh: "Vercel"
  github.io: "GitHub Pages"
  githubusercontents: "GitHub"
  gitlab: "GitLab Pages"
  b-cdn: "BunnyCDN"
  bunnycdn: "BunnyCDN"
  cachefly: "CacheFly"
  edgecast: "Edgecast/Verizon"
  llnwd: "Limelight"
  lldns: "Limelight"
  footprint: "CenturyLink CDN"
  bitgravity: "BitGravity"
  instacontent: "Mirror Image"
  cdnetworks: "CDNetworks"
  cdnsun: "CDNsun"
  keycdn: "KeyCDN"
  kxcdn: "KeyCDN"
  cdn77: "CDN77"
  r.worldcdn: "CDN77"
  quantil: "Quantil/ChinaCache"
  swiftcdn1: "SwiftCDN"
  swiftserve: "SwiftCDN"
  transloadit: "Transloadit"
  section.io: "Section.io"
  caspowa: "Caspowa"
  twimg: "Twitter CDN"
  fbcdn: "Facebook CDN"
  rncdn: "RocketCDN"
  doracdn: "Dora CDN"
  yottaa: "Yottaa"
  cdn-apple: "Apple CDN"
  zenedge: "Zenedge"

# HTTP Header Patterns - HTTP头部特征
header_patterns:
  cf-ray: "Cloudflare"
  cf-cache-status: "Cloudflare"
  cf-request-id: "Cloudflare"
  x-amz-cf-id: "AWS CloudFront"
  x-amz-cf-pop: "AWS CloudFront"
  x-akamai: "Akamai"
  x-akamai-transformed: "Akamai"
  akamai-origin-hop: "Akamai"
  x-cache-key: "Akamai"
  x-true-cache-key: "Akamai"
  x-fastly-request-id: "Fastly"
  fastly-debug-digest: "Fastly"
  x-served-by: "Fastly"
  x-msedge-ref: "Azure CDN"
  x-azure-ref: "Azure CDN"
  x-ec-custom-error: "Edgecast"
  x-cdn: "Various CDN"
  x-cdn-geo: "Various CDN"
  x-cache-hit: "Various CDN"
  x-proxy-cache: "Various CDN"
  x-tengine-debug: "阿里云CDN"
  eagleid: "阿里云CDN"
  x-swift-savetime: "阿里云CDN"
  x-swift-cachetime: "阿里云CDN"
  x-via: "网宿CDN"
  x-ws-request-id: "网宿CDN"
  x-ser: "网宿CDN"
  x-cache-lookup: "网宿CDN"
  via-tencent: "腾讯云CDN"
  x-nws-log-uuid: "腾讯云CDN"
  x-daa-tunnel: "腾讯云CDN"
  x-cache-status: "腾讯云CDN"
  x-bce-request-id: "百度云CDN"
  x-bd-traceid: "百度云CDN"
  server-timing: "Various CDN"
  x-hw-response: "华为云CDN"
  x-huawei: "华为云CDN"
  x-jd-cache: "京东云CDN"
  x-request-id: "Various CDN"
  x-upyun-request-id: "又拍云CDN"
  x-qnm-cache: "七牛云CDN"
  x-qiniu-zone: "七牛云CDN"
  x-sucuri-id: "Sucuri"
  x-sucuri-cache: "Sucuri"
  x-iinfo: "Imperva"
  x-cdn-provider: "Various CDN"
  powered-by-chinacache: "蓝汛CDN"
  x-source: "Various CDN"
  x-edge-ip: "Various CDN"
  x-edge-location: "Various CDN"

# CDN IP Ranges - CDN IP段 (CIDR)
ip_ranges:
  Cloudflare:
    - "173.245.48.0/20"
    - "103.21.244.0/22"
    - "103.22.200.0/22"
    - "103.31.4.0/22"
    - "141.101.64.0/18"
    - "108.162.192.0/18"
    - "190.93.240.0/20"
    - "188.114.96.0/20"
    - "197.234.240.0/22"
    - "198.41.128.0/17"
    - "162.158.0.0/15"
    - "104.16.0.0/13"
    - "104.24.0.0/14"
    - "172.64.0.0/13"
    - "131.0.72.0/22"

  Fastly:
    - "23.235.32.0/20"
    - "43.249.72.0/22"
    - "103.244.50.0/24"
    - "103.245.222.0/23"
    - "103.245.224.0/24"
    - "104.156.80.0/20"
    - "140.248.64.0/18"
    - "140.248.128.0/17"
    - "146.75.0.0/17"
    - "151.101.0.0/16"
    - "157.52.64.0/18"
    - "167.82.0.0/17"
    - "167.82.128.0/20"
    - "167.82.160.0/20"
    - "167.82.224.0/20"
    - "172.111.64.0/18"
    - "185.31.16.0/22"
    - "199.27.72.0/21"
    - "199.232.0.0/16"

  Akamai:
    - "23.0.0.0/12"
    - "23.32.0.0/11"
    - "23.64.0.0/14"
    - "23.72.0.0/13"
    - "104.64.0.0/10"

  AWS_CloudFront:
    - "3.164.128.0/17"
    - "3.165.0.0/16"
    - "3.166.0.0/15"
    - "3.168.0.0/13"
    - "13.32.0.0/15"
    - "13.35.0.0/16"
    - "13.224.0.0/14"
    - "13.249.0.0/16"
    - "18.64.0.0/14"
    - "18.154.0.0/15"
    - "52.46.0.0/18"
    - "52.82.128.0/19"
    - "52.84.0.0/15"
    - "54.182.0.0/16"
    - "54.192.0.0/16"
    - "54.230.0.0/17"
    - "54.239.128.0/18"
    - "54.239.192.0/19"
    - "64.252.64.0/18"
    - "64.252.128.0/18"
    - "65.8.0.0/16"
    - "65.9.0.0/17"
    - "65.9.128.0/18"
    - "70.132.0.0/18"
    - "71.152.0.0/17"
    - "99.84.0.0/16"
    - "99.86.0.0/16"
    - "108.156.0.0/14"
    - "108.138.0.0/15"
    - "116.129.226.0/25"
    - "116.129.226.128/26"
    - "120.52.12.64/26"
    - "120.52.22.96/27"
    - "120.52.39.128/27"
    - "120.52.153.192/26"

  Azure_CDN:
    - "13.107.246.0/24"
    - "13.107.213.0/24"
    - "147.243.0.0/16"
