# Favicon 哈希指纹库
# 用于通过 favicon 识别 CMS/框架

favicon_hashes:
  # Murmur3 Hash -> 产品名称
  "-247388890": "Kubernetes Dashboard"
  "-1293239800": "Apache Tomcat"
  "-1948371805": "Spring Boot"
  "116323821": "Jenkins"
  "1485257654": "Grafana"
  "-1840324437": "GitLab"
  "1697030106": "Nexus"
  "-2057558656": "Zabbix"
  "-620529849": "phpMyAdmin"
  "1165982963": "Prometheus"
  "1522876098": "Elasticsearch"
  "-1379982221": "Kibana"
  "999357577": "RabbitMQ"
  "-305179312": "Consul"
  "-697606513": "Nacos"
  "81586312": "MinIO"
  "-1278018848": "Rancher"
  "1165824036": "Harbor"
  "-66419837": "SonarQube"
  "-1456538498": "Portainer"
  "989289239": "JBoss"
  "-1197506026": "WebLogic"
  "-1820030572": "Webmin"
  "1485257654": "Grafana"
  "-1003280392": "Nginx"
  "602431901": "Apache"
  "116323821": "Jenkins"
  "-289492017": "WordPress"
  "-674708115": "Joomla"
  "1165982963": "Drupal"
  "1917787012": "ThinkPHP"
  "-1377548940": "Laravel"
  "-1950415971": "Django"
  "-1166125415": "Flask"
  "1550890147": "Vue.js"
  "-956942908": "React"
  "-1396567049": "Angular"
  "-1018559840": "Node.js"
  "-1420604883": "Express"
  "81586312": "Golang"
  "-1395093860": "Ruby on Rails"
  "-1950415971": "FastAPI"
  "-1379982221": "Swagger"
  "-1572415279": "OpenAPI"
  "766298376": "Outlook"
  "-1293239800": "IIS"
  "142762289": "Citrix"
  "-1137810503": "VMware"
  "-1200912501": "Confluence"
  "-1095087783": "Jira"
  "-620529849": "Adminer"
  "-1820030572": "CPanel"
  "-1248692954": "Plesk"
  "-1018559840": "DirectAdmin"
  "-1456538498": "Docker"
  "-305179312": "Kubernetes"
  "-697606513": "Istio"
  "-1278018848": "OpenShift"
  "1165824036": "AWS"
  "-66419837": "Azure"
  "-1137810503": "GCP"
  "-1095087783": "Alibaba Cloud"
  "-1200912501": "Tencent Cloud"
  "1917787012": "Huawei Cloud"
  "-1377548940": "Baidu Cloud"
  "-289492017": "Discuz"
  "-674708115": "Typecho"
  "-1166125415": "Hexo"
  "1550890147": "Hugo"
  "-956942908": "Ghost"
  "-1396567049": "Gatsby"
  "-1420604883": "Next.js"
  "-1395093860": "Nuxt.js"
  "-1572415279": "VuePress"
  "766298376": "Docsify"
  "142762289": "MkDocs"
  "-1248692954": "Sphinx"

# MD5 Hash -> 产品名称
favicon_md5:
  "d41d8cd98f00b204e9800998ecf8427e": "Empty"
  "3ca96758aa9e76073a65eba4f42f2f6c": "Apache"
  "f9c96e0c67b6a93a40c76c7ee0c43c33": "Nginx"
  "709dd38f2b5fcc7e98ef8f8ed0e9e12f": "IIS"
  "4e36c54c8f26c0c0cd3c4e4f5b5e0e7a": "Tomcat"
  "8a9c67c7e7c5e5e8b8c7e8e8c7e7c7e7": "Jenkins"
  "a9b8c7d6e5f4g3h2i1j0k9l8m7n6o5p4": "GitLab"
